name: firebase_admob_example
description: Demonstrates how to use the firebase_admob plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_admob:
    path: ../
  firebase_core:
    path: ../../firebase_core/firebase_core

dependency_overrides:
  firebase_core:
    path: ../../firebase_core/firebase_core

dev_dependencies:
  pedantic: ^1.8.0
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
