name: moor
description: Moor is a safe and reactive persistence library for Dart applications
version: 2.0.1
repository: https://github.com/simolus3/moor
homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues
authors:
  - Simon Binder <oss@simonbinder.eu>
maintainer: Simon Binder (@simolus3)

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  meta: ^1.0.0
  convert: ^2.1.1
  collection: ^1.0.0
  synchronized: ^2.1.0
  pedantic: ^1.0.0

dev_dependencies:
  moor_generator: ^2.0.0
  build_runner: '>=1.3.0 <2.0.0'
  build_test: ^0.10.8
  test: ^1.6.4
  mockito: ^4.1.0
  grinder: ^0.8.3
  coverage: any # will be determined by test_coverage
  test_coverage: ^0.3.0

#dependency_overrides:
#  moor_generator:
#    path: ../moor_generator
#  sqlparser:
#    path: ../sqlparser