name: synchronized
description: Lock mechanism to prevent concurrent access to asynchronous code.
version: 2.1.0+1
author:  Tekartik <dev@tekartik.com>
homepage: https://github.com/tekartik/synchronized.dart

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  test: '>=1.5.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  build_runner: '>=0.9.2'
  build_test: '>=0.10.3'
  build_web_compilers: '>=1.1.0'

