name: firebase_analytics_platform_interface
description: A common platform interface for the firebase_analytics plugin.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.3

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.5 <2.0.0"
