name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

dependencies:
  firebase_analytics: ^6.0.2
  flutter:
    sdk: flutter
  firebase_messaging:
    path: ../
  firebase_core: 
    path: ../../firebase_core/firebase_core

dependency_overrides:
  firebase_core:
    path: ../../firebase_core/firebase_core

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
