name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager:
    path: ../
  cupertino_icons: ^1.0.2
  url_launcher: ^5.4.11
  baseflow_plugin_template:
    git:
      url: git://github.com/Baseflow/baseflow_plugin_template.git
      ref: v1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - packages/baseflow_plugin_template/logo.png
    - packages/baseflow_plugin_template/poweredByBaseflow.png
