name: firebase_admob
description: Flutter plugin for Firebase AdMob, supporting
  banner, interstitial (full-screen), and rewarded video ads
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob
version: 0.11.0+1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebaseadmob
        pluginClass: FirebaseAdMobPlugin
      ios:
        pluginClass: FLTFirebaseAdMobPlugin

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
dev_dependencies:
  pedantic: ^1.8.0
  flutter_driver:
    sdk: flutter
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter
  e2e: ^0.6.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
