name: moor
description: Moor is a safe and reactive persistence library for Dart applications
version: 4.2.1
repository: https://github.com/simolus3/moor
homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0
  convert: "^3.0.0"
  collection: ^1.15.0
  meta: ^1.3.0
  pedantic: ^1.10.0
  stream_channel: ^2.1.0
  sqlite3: ">=0.1.9-nullsafety <2.0.0"

dev_dependencies:
  build_test: ^2.0.0
  build_runner_core: ^6.1.0
  moor_generator: any
  uuid: ^3.0.0-nullsafety.0
  path: ^1.8.0-nullsafety.3
  build_runner: ^1.10.4
  test: ^1.16.0
  mockito: ^5.0.0-nullsafety.7
  rxdart: ^0.26.0-nullsafety

#dependency_overrides:
#  moor_generator:
#    path: ../moor_generator
#  sqlparser:
#    path: ../sqlparser